# Generated by Django 6.0.4 on 2026-05-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_avatar_account_bio'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='گروه بندی کاربران را انجام دهید', related_name='account_set', related_query_name='user', to='auth.group', verbose_name='گروه ها'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='اجازه کاربران را بدهید', related_name='account_set_permissions', related_query_name='user', to='auth.permission', verbose_name='اجازه ها'),
        ),
    ]
