# Generated by Django 6.0.4 on 2026-04-20 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع')),
                ('summary', models.TextField(verbose_name='خلاصه متن')),
                ('description', models.TextField(verbose_name='متن اصلی')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='تصویر شاخص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='مورد تایید')),
                ('is_pin', models.BooleanField(default=False, verbose_name='سنجاق شده')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-write_date'],
            },
        ),
    ]
