# Generated by Django 6.0.4 on 2026-04-29 08:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.Post.thumbnail_upload_path, verbose_name='تصویر شاخص'),
        ),
    ]
