# Generated by Django 6.0.4 on 2026-05-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشته شدن')),
                ('old_content', models.TextField(blank=True, null=True, verbose_name='محتوا قبل ویرایش')),
                ('edited', models.BooleanField(default=False, verbose_name='تغییر یافته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='تایید')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-write_date'],
                'abstract': False,
            },
        ),
    ]
