# Generated by Django 6.0.4 on 2026-05-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postcomment'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='محتوا'),
        ),
    ]
