# Generated by Django 6.0.4 on 2026-05-22 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان')),
                ('code_file', models.FileField(blank=True, help_text='اگر کد شما خیلی طولانی است،کد را بارگذاری کنید', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'pyi', 'pyw', 'pyt', 'js', 'ts', 'jsx', 'tsx', 'c', 'cc', 'cpp', 'h', 'hpp', 'cs', 'java', 'kt', 'scala', 'swift', 'go', 'rs', 'rb', 'php', 'dart', 'html', 'htm', 'css', 'scss', 'sass', 'less', 'sql', 'r', 'ipynb', 'sas', 'jl', 'sh', 'bash', 'zsh', 'ps1', 'bat', 'cmd', 'pl', 'pm', 'lua', 'tcl', 'asm', 's', 'm', 'mm', 'pas', 'd', 'nim', 'v', 'vhdl', 'verilog', 'f', 'for', 'f90', 'hs', 'lhs', 'clj', 'cljs', 'lisp', 'scm', 'erl', 'hrl', 'ex', 'exs', 'fs', 'fsi', 'ml', 'mli', 'pro', 'ada', 'cob', 'json', 'yaml', 'yml', 'toml', 'xml', 'ini', 'conf', 'toml', 'properties', 'md', 'rst', 'tex'])], verbose_name='فایل کد')),
                ('description', models.TextField(help_text='مشکلات،توضیحات و کد را به اشتراک بگذارید', verbose_name='توضیحات')),
                ('ask_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرسش')),
                ('hide_user', models.BooleanField(default=False, verbose_name='پنهان شدن هویت پرسشگر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن پرسش')),
                ('is_pin', models.BooleanField(verbose_name='سنجاق کردن سوال')),
                ('is_verify', models.BooleanField(verbose_name='مورد تایید بودن سوال')),
                ('is_solve', models.BooleanField(default=False, verbose_name='حل شدن سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='پرسشگر')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_best', models.BooleanField(default=False, verbose_name='بهترین')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مطرح شدن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='q_a.question')),
            ],
        ),
    ]
