# Generated by Django 6.0.4 on 2026-05-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hide_user',
        ),
    ]
